// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


case class Entry2(episode: Int,
  status: Int,
  score: Int,
  storage_type: scalaxb.DataRecord[Any],
  storage_value: scalaxb.DataRecord[Any],
  times_rewatched: scalaxb.DataRecord[Any],
  rewatch_value: scalaxb.DataRecord[Any],
  date_start: scalaxb.DataRecord[Any],
  date_finish: scalaxb.DataRecord[Any],
  priority: scalaxb.DataRecord[Any],
  enable_discussion: scalaxb.DataRecord[Any],
  enable_rewatching: scalaxb.DataRecord[Any],
  comments: scalaxb.DataRecord[Any],
  tags: String)
      

